name: Deploy Frontend to Server

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci
        working-directory: ./frontend

      - name: Build project
        run: npm run build
        working-directory: ./frontend

      - name: Deploy to Server via SCP
        uses: appleboy/scp-action@v0.1.4
        with:
          host: 211.188.62.223
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "frontend/build/"
          target: "/var/www/frontend"
          overwrite: true
          strip_components: 0

      - name: Check files on remote server
        uses: appleboy/ssh-action@master
        with:
          host: 211.188.62.223
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            ls -al /var/www/frontend/index.html