name: Frontend CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend-vite/**'
      - '.github/workflows/frontend-deploy.yml'
  workflow_dispatch: {}

permissions:
  contents: read

concurrency:
  group: frontend-deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend-vite
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: frontend-vite/package-lock.json

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      # 배포: 원격 서버로 dist/ 동기화 (rsync over SSH)
      - name: Deploy via rsync
        uses: easingthemes/ssh-deploy@v5.0.3
        with:
          sshPrivateKey: ${{ secrets.SSH_PRIVATE_KEY }}
          remoteHost: ${{ secrets.SSH_HOST }}
          remoteUser: ${{ secrets.SSH_USER }}
          remotePort: ${{ secrets.SSH_PORT || '22' }}
          # 워크스페이스 기준 경로
          source: 'frontend-vite/dist/'
          # 예: /var/www/siseon-frontend 또는 Nginx 정적 루트
          target: ${{ secrets.DEPLOY_PATH }}
          args: '-az --delete'


